name: recipe_finder
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_gif: ^0.0.4
  google_fonts: any
  http: any
  meta: ^1.9.1
  translator: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  rename: ^2.1.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: assets/logo.png
  android: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/
