name: recipe_finder
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: any
  translator: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  rename: ^2.1.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: assets/logo.png
  android: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/
